### ISSUE TITLE
Base Quantity

### ISSUE THREAD

**Issue by ThomasSFTI** [OpenPEPPOL/pracc-catalogue#48]
In some cases, when offering a price, the price may be very low, In these cases you may need to use a Base Quantity to express the price i a larger volume. I.e price for 1000 is 2.00 SEK (instead of price is 0.002 SEK per unit).
When procuring goods and services there can be a question in the Pre award catalogue request about offering a product, for example paper. There must be a base quantity, i e  saying that the offer shall be the price for 1.000 papers/pieces or if something shall be  offered per liter or kg.

So,  if not this is specified in the procurement documents there must be a base quantity in the pre award catalogue request and therfore also in the pre award catalogue so that the contracting authority can compare and evaluate  different offers/tender.

This is also used in the PostAward Catalogue.

**Comment by SiwMeckelborg** [comment]
Check reason with Veit, as to why the BaseQuantity has been removed in BII3. Send email and make decision when we get the response.

**Comment by idolum** [comment]
In BII3 the modeling of prices and quantities was reviewed. Due to this review, the classes "Item comparison" and "Catalogue item price" were introduced. In the class "Item comparison" you can specify the "base" that can be used by a contracting authority to compare the price. 

CEN/TC 440/WG 5 will base its specifications on the CWA 17028:2016. So, it will be the same there. But this is not set in stone. If it turns out that it the specification is not applicable to all use cases, it can be changed. But should be compatible to the existing class "Item comparison" and not add redundancy to the transaction data model of the catalogue.

**Comment by SiwMeckelborg** [comment]
Closing this based on no further feedback from issue owner
